name: flutter_countries 
description: Query and retrieve country details by property type from a database of 250 countries.
version: 1.0.1
repository: https://github.com/p4-k4/flutter_countries

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/countries.json
    - lib/assets/cities.json
    - lib/assets/states.json